// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCx9ntWZ6CvZOwVbMsV6FmOa_Ja7bkanaA',
    appId: '1:499356205487:web:f2468d0996a0f7f0c1af5a',
    messagingSenderId: '499356205487',
    projectId: 'safestreetibm',
    authDomain: 'safestreetibm.firebaseapp.com',
    storageBucket: 'safestreetibm.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDbynm_0o-mzeburpJbj0YfG_72-elt8RE',
    appId: '1:499356205487:android:05632c22cce35703c1af5a',
    messagingSenderId: '499356205487',
    projectId: 'safestreetibm',
    storageBucket: 'safestreetibm.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAK1T9-gLfD2K4UOSaES_e7eCD2peBw9oU',
    appId: '1:499356205487:ios:878d8f8a3830fefdc1af5a',
    messagingSenderId: '499356205487',
    projectId: 'safestreetibm',
    storageBucket: 'safestreetibm.appspot.com',
    iosBundleId: 'com.example.safestreet',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAK1T9-gLfD2K4UOSaES_e7eCD2peBw9oU',
    appId: '1:499356205487:ios:878d8f8a3830fefdc1af5a',
    messagingSenderId: '499356205487',
    projectId: 'safestreetibm',
    storageBucket: 'safestreetibm.appspot.com',
    iosBundleId: 'com.example.safestreet',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCx9ntWZ6CvZOwVbMsV6FmOa_Ja7bkanaA',
    appId: '1:499356205487:web:e01c84f094531d1cc1af5a',
    messagingSenderId: '499356205487',
    projectId: 'safestreetibm',
    authDomain: 'safestreetibm.firebaseapp.com',
    storageBucket: 'safestreetibm.appspot.com',
  );
}
